<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Folder Include="Entites\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NTier.SharedKernel\NTier.SharedKernel.csproj" />
  </ItemGroup>

</Project>
