<Project Sdk="Microsoft.NET.Sdk">
	
	<ItemGroup>

		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Scrutor" />
		<PackageReference Include="Serilog" />
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\NTier.Database\NTier.Database.csproj" />
	  <ProjectReference Include="..\NTier.SharedKernel\NTier.SharedKernel.csproj" />
	</ItemGroup>

</Project>
